<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Product::truncate();
        Schema::enableForeignKeyConstraints();
        $products = [
            // SAYURAN (Ikat)
            [
                'nama_produk' => 'Selada Keriting Hijau',
                'deskripsi' => 'Selada hidroponik segar, tanpa pestisida, ditanam dengan sistem NFT.',
                'harga' => 15000,
                'jumlah_stok' => 50,
                'kategori' => 'Sayuran',
                'berat' => 250,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Pakcoy Hidroponik',
                'deskripsi' => 'Pakcoy renyah kualitas premium, sangat segar.',
                'harga' => 12000,
                'jumlah_stok' => 45,
                'kategori' => 'Sayuran',
                'berat' => 300,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Kangkung Hidroponik',
                'deskripsi' => 'Kangkung segar hasil budidaya hidroponik.',
                'harga' => 8000,
                'jumlah_stok' => 60,
                'kategori' => 'Sayuran',
                'berat' => 200,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bayam Hijau',
                'deskripsi' => 'Bayam hijau segar kaya zat besi.',
                'harga' => 10000,
                'jumlah_stok' => 40,
                'kategori' => 'Sayuran',
                'berat' => 200,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bayam Merah',
                'deskripsi' => 'Bayam merah premium, tinggi antioksidan.',
                'harga' => 12000,
                'jumlah_stok' => 30,
                'kategori' => 'Sayuran',
                'berat' => 200,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Sawi Hijau (Caisim)',
                'deskripsi' => 'Sawi hijau renyah untuk berbagai masakan.',
                'harga' => 10000,
                'jumlah_stok' => 50,
                'kategori' => 'Sayuran',
                'berat' => 300,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Sawi Putih',
                'deskripsi' => 'Sawi putih segar ukuran sedang.',
                'harga' => 15000,
                'jumlah_stok' => 25,
                'kategori' => 'Sayuran',
                'berat' => 500,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Kale Keriting',
                'deskripsi' => 'Superfood kale keriting, sangat sehat.',
                'harga' => 25000,
                'jumlah_stok' => 15,
                'kategori' => 'Sayuran',
                'berat' => 200,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Sawi Pagoda',
                'deskripsi' => 'Sawi pagoda unik dengan tekstur renyah.',
                'harga' => 20000,
                'jumlah_stok' => 20,
                'kategori' => 'Sayuran',
                'berat' => 250,
                'unit' => 'Ikat',
                'is_delete' => false,
            ],

            // ALAT (Pcs)
            [
                'nama_produk' => 'Netpot Hitam 5cm',
                'deskripsi' => 'Netpot standar untuk hidroponik.',
                'harga' => 1500,
                'jumlah_stok' => 500,
                'kategori' => 'Alat',
                'berat' => 10,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Netpot Putih 7cm',
                'deskripsi' => 'Netpot ukuran lebih besar untuk tanaman besar.',
                'harga' => 2500,
                'jumlah_stok' => 300,
                'kategori' => 'Alat',
                'berat' => 15,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'TDS Meter Digital',
                'deskripsi' => 'Alat ukur kepekatan nutrisi air.',
                'harga' => 45000,
                'jumlah_stok' => 40,
                'kategori' => 'Alat',
                'berat' => 150,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'pH Meter Digital',
                'deskripsi' => 'Alat ukur tingkat keasaman air.',
                'harga' => 65000,
                'jumlah_stok' => 30,
                'kategori' => 'Alat',
                'berat' => 150,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Pompa Celup 15W',
                'deskripsi' => 'Pompa air efisien untuk sirkulasi nutrisi.',
                'harga' => 85000,
                'jumlah_stok' => 20,
                'kategori' => 'Alat',
                'berat' => 500,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Tray Semai 128 Lubang',
                'deskripsi' => 'Wadah untuk persemaian bibit.',
                'harga' => 18000,
                'jumlah_stok' => 100,
                'kategori' => 'Alat',
                'berat' => 300,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Rockwool Cultilene Slab',
                'deskripsi' => 'Media tanam rockwool kualitas terbaik.',
                'harga' => 65000,
                'jumlah_stok' => 50,
                'kategori' => 'Alat',
                'berat' => 500,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Kain Flanel Sumbu',
                'deskripsi' => 'Kain flanel penyerap air untuk sistem wick.',
                'harga' => 5000,
                'jumlah_stok' => 200,
                'kategori' => 'Alat',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Pipa PVC Hidroponik 2 Inch',
                'deskripsi' => 'Pipa PVC khusus dengan lubang tanam.',
                'harga' => 55000,
                'jumlah_stok' => 40,
                'kategori' => 'Alat',
                'berat' => 1000,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],

            // NUTRISI (Pcs)
            [
                'nama_produk' => 'AB Mix Sayur Daun 1L',
                'deskripsi' => 'Nutrisi lengkap untuk sayuran daun.',
                'harga' => 35000,
                'jumlah_stok' => 80,
                'kategori' => 'Nutrisi',
                'berat' => 1000,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'AB Mix Buah 1L',
                'deskripsi' => 'Nutrisi khusus untuk tanaman buah.',
                'harga' => 45000,
                'jumlah_stok' => 50,
                'kategori' => 'Nutrisi',
                'berat' => 1000,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'AB Mix Umum 1L',
                'deskripsi' => 'Nutrisi serbaguna untuk segala tanaman.',
                'harga' => 40000,
                'jumlah_stok' => 60,
                'kategori' => 'Nutrisi',
                'berat' => 1000,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'POC Organik Cair',
                'deskripsi' => 'Pupuk organik cair untuk kesuburan tanah/air.',
                'harga' => 25000,
                'jumlah_stok' => 40,
                'kategori' => 'Nutrisi',
                'berat' => 500,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'ZPT Hormon Tumbuh',
                'deskripsi' => 'Zat pengatur tumbuh untuk mempercepat akar.',
                'harga' => 30000,
                'jumlah_stok' => 30,
                'kategori' => 'Nutrisi',
                'berat' => 250,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Pestisida Nabati 500ml',
                'deskripsi' => 'Pembasmi hama alami yang aman.',
                'harga' => 35000,
                'jumlah_stok' => 35,
                'kategori' => 'Nutrisi',
                'berat' => 500,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Fungisida Organik',
                'deskripsi' => 'Mencegah jamur pada akar tanaman.',
                'harga' => 40000,
                'jumlah_stok' => 25,
                'kategori' => 'Nutrisi',
                'berat' => 500,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Nutrisi Mikro Tambahan',
                'deskripsi' => 'Pelengkap unsur mikro tanaman.',
                'harga' => 20000,
                'jumlah_stok' => 40,
                'kategori' => 'Nutrisi',
                'berat' => 100,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],

            // BIBIT (Pcs)
            [
                'nama_produk' => 'Bibit Selada Unggul',
                'deskripsi' => 'Bibit selada dengan daya tumbuh 95%.',
                'harga' => 5000,
                'jumlah_stok' => 200,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Pakcoy Nauli F1',
                'deskripsi' => 'Bibit pakcoy kualitas hibrida.',
                'harga' => 5000,
                'jumlah_stok' => 150,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Kangkung Bangkok',
                'deskripsi' => 'Bibit kangkung daun lebar.',
                'harga' => 5000,
                'jumlah_stok' => 300,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Bayam Cabut',
                'deskripsi' => 'Bibit bayam cepat panen.',
                'harga' => 5000,
                'jumlah_stok' => 250,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Tomat Cherry Red',
                'deskripsi' => 'Bibit tomat cherry manis.',
                'harga' => 10000,
                'jumlah_stok' => 100,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Cabe Rawit Unggul',
                'deskripsi' => 'Bibit cabe rawit tahan penyakit.',
                'harga' => 10000,
                'jumlah_stok' => 120,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Terong Ungu',
                'deskripsi' => 'Bibit terong ungu produktif.',
                'harga' => 8000,
                'jumlah_stok' => 90,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Melon Premium',
                'deskripsi' => 'Bibit melon hidroponik manis.',
                'harga' => 15000,
                'jumlah_stok' => 50,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
            [
                'nama_produk' => 'Bibit Semangka Inul',
                'deskripsi' => 'Bibit semangka tanpa biji.',
                'harga' => 15000,
                'jumlah_stok' => 50,
                'kategori' => 'Bibit',
                'berat' => 50,
                'unit' => 'Pcs',
                'is_delete' => false,
            ],
        ];

        foreach ($products as $product) {
            $product['slug'] = Str::slug($product['nama_produk']);
            $product['foto_produk'] = [];
            Product::create($product);
        }
    }
}
